### ISSUE TITLE
On debian11 service throws warning

### ISSUE THREAD

**Issue by yakari007** [plusclouds/vmOperations#3]
<string>:22: DeprecationWarning: distro.linux_distribution() is deprecated. It should only be used as a compatibility shim with Python's platform.linux_distribution(). Please use distro.id(), distro.version() and distro.name() instead.
<string>:22: DeprecationWarning: distro.linux_distribution() is deprecated. It should only be used as a compatibility shim with Python's platform.linux_distribution(). Please use distro.id(), distro.version() and distro.name() instead.

**Comment by unsel** [comment]
Fixed the warning by using distro.id() and distro.version() instead of deprecated distro.linux_distribution()
